# This is a config for E2B sandbox template.
# You can use template ID (aut93bg3z6i2klylqlkv) or template name (vibe-nextjs) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs')

team_id = "6e155876-04af-4c77-98fa-2fc39d4a264e"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs"
template_id = "aut93bg3z6i2klylqlkv"
